### ISSUE TITLE
Allow more than two indices in EXCEPT clauses

### ISSUE THREAD

**Issue by ToddFincannon** [climateinteractive/SDEverywhere#117]
When a subscript in an EXCEPT clause is an index, it causes the variable to be separated on that dimension.

This var is separated on all three subscriptis:
```
except3[DimD, DimE, DimF] :EXCEPT: [D2, E2, F2] = 3 ~~|
```

But this one on only two:
```
except2[DimD, DimE, DimF] :EXCEPT: [D2, E2, DimF] = 2 ~~|
```

SDEverywhere currently only supports expansion on two subscripts in an except clause. The first var shown above ignores the EXCEPT clause, resulting in assignment to every index in the 3D subscript range:

```
// except3[DimD,DimE,DimF]:EXCEPT:[D2,E2,F2] = 3
for (size_t i = 0; i < 2; i++) {
  for (size_t j = 0; j < 2; j++) {
    for (size_t k = 0; k < 2; k++) {
      _except3[i][j][k] = 3.0;
    }
  }
}
```

We need to expand this to at least three subscripts, and preferably any number.

**Comment by ToddFincannon** [comment]
The solution to this problem built on the `VariableReader` work from last week. It turned out that the step to further generalize that solution to expanding any number of subscripts led to a rewrite of `expandVars` that is much simpler than what we had before. This affects not only EXCEPT clauses, but all expansions of variables into separated indices.

**Comment by jrissman** [comment]
@ToddFincannon Todd, your technique of using the Cartesian product to expand and process subscripts is really powerful.  It's amazing that it makes the code so much shorter and more elegant than before, while simultaneously generalizing it to handle any number of subscripts.  This is going to be useful not only in EXCEPT clauses, but for processing variables with more than 3 dimensions more generally.  @chrispcampbell - don't miss this cool approach!

**Comment by ToddFincannon** [comment]
@jrissman I thought of the cartesian product technique for flattening nested loops that day we were in the office together. When I went to add an array product function, I found that @chrispcampbell had already added one. So Chris thought of it first.

**Comment by chrispcampbell** [comment]
@jrissman @ToddFincannon It is indeed a cool approach!  I've used it in quite a few projects now, most recently on the forthcoming model-check project.  Really handy for testing a ton of combinations with really terse code.

**Comment by jrissman** [comment]
@ToddFincannon @chrispcampbell Boy are we lucky that we have you two brilliant software engineers working to help stop climate change!
