### ISSUE TITLE
fimodule in sde-generate.js?

### ISSUE THREAD

**Issue by Karaka** [climateinteractive/SDEverywhere#130]
reference to this module appears at line 299 of the sde-generate file (in the develop branch code).

is this the right source:
https://pypi.org/project/fimodule/

thank you...Alan

**Comment by chrispcampbell** [comment]
@Karaka I don't see any references to a "fimodule" in SDEverywhere.  If it's important, can you please provide a direct link to where you saw it referenced?

The Discussions page is probably a better place for general Q&A related to SDEverywhere.  The board is empty thus far, but feel free to ask questions here:
https://github.com/climateinteractive/SDEverywhere/discussions/categories/q-a

**Comment by Karaka** [comment]
Will do Chris…and thanks for getting back so quickly.

 

Understood re the discussions board.

 

Cheers and bon weekend,

Alan

**Comment by Karaka** [comment]
When I checked back with Github source code Chris, sure enough there were no references to “fimodule”. 

 

Sorry for the false alarm… I must have corrupted my local file and should’ve checked back earlier!

 

Best, Alan

 

Alan Plunkett

Director Karaka Limited

https://uk.linkedin.com/pub/alan-plunkett/8/2a7/2a9
