### ISSUE TITLE
Generating C code is slow for EPS

### ISSUE THREAD

**Issue by ToddFincannon** [climateinteractive/SDEverywhere#167]
Generating C code for the EPS model takes 108 seconds on my Mac, which seems way too slow.

```
time node src/sde.js generate --genc --spec ~/Projects/eps-sde/co2e_spec.json ~/Projects/eps-sde/eps.mdl
```

**Comment by ToddFincannon** [comment]
Following Chris's advice in #62, I tried the Clinic Flame profiler. It crashed when running sde generate, so I tried the [0x project](https://github.com/davidmarkclements/0x) that is is based on.

```
0x -- node src/sde.js generate --genc --spec ~/Projects/eps-sde/co2e_spec.json ~/Projects/eps-sde/eps.mdl
```

This worked, although the flame graph is not as nice. However, the problem is clearly the `readCsv` function.

<img width="3008" alt="before" src="https://user-images.githubusercontent.com/987498/142559047-0ceafeee-72a6-4cb6-8a72-cf7bb5c7d4b3.png">

A quick check showed that `readCsv` is called repeatedly for the same file. This is because multiple equations in EPS use `GET DIRECT DATA` for one row or column of a CSV file — in one case, resulting in the same rather large CSV file being read and parsed 2725 times.

The solution is to cache the parsed CSV files so they are only read once. This reduced `sde generate` time from 108 to 20 seconds.

After this, the profiler did not show any standout CPU hogs, so I am satisfied with ending optimization efforts here.

<img width="3008" alt="after" src="https://user-images.githubusercontent.com/987498/142559812-8dd906bb-c616-4417-8238-0fd4eeb6ba1d.png">

**Comment by ToddFincannon** [comment]
There is an additional problem that comes up when we generate code for the full output variable list in EPS. The speedup here was only 2.5x instead of 5x for the previous example with only one output variable.

<img width="3008" alt="recordRefsOfVariable" src="https://user-images.githubusercontent.com/987498/142573633-7e0ee4be-a4c4-41ab-ae9b-530d156e4900.png">

Here `recordRefsOfVariable` goes into a deep recursion that takes a lot of time. It's hard to see what we can do about this. The variable lookup is already in a hash table, and we are stuck with the recursion due to the nature of the model structure.

**Comment by chrispcampbell** [comment]
@ToddFincannon I was just about to point you at `referencedRefIds` and suggest trying a Set (or revamping that code in general) but you beat me to it.  The idea behind `referencedRefIds` was to eliminate further (redundant) processing; I can see now that a Set would've been more appropriate there.  I'm curious if that search is where the time is being spent in that graph above, or if there's something else going on.  Let me know if you have other ideas to speed that code up; I don't think I spent too much time tuning it.

**Comment by ToddFincannon** [comment]
Using a Set reduced the genc time from 60 to 19.3 seconds — well worthwhile! Now I think we're done.

<img width="3008" alt="recordRefsOfVariable2" src="https://user-images.githubusercontent.com/987498/142577265-9efedae0-9cdc-49e6-8218-99bf731e2cb7.png">
