### ISSUE TITLE
Update csv-parse in plugin-config package and update option names in compile package

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/SDEverywhere#299]
The `csv-parse` dependency was updated in the `compile` package yesterday, but the one in the `plugin-config` package wasn't updated.  We should update that one too so that we don't impose two versions on users.

**Comment by ToddFincannonEI** [comment]
Good catch! Note this update requires a change in the import.

```js
import { parse as parseCsv } from 'csv-parse/sync'
```
