### ISSUE TITLE
Reduce build time by running more steps in parallel 

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/SDEverywhere#347]
We currently run the build steps sequentially in the GitHub Actions `build` workflow.  This makes the flow conceptually easy to understand (workspace dependencies are built in the correct order) and makes the logs flow sequentially, but it doesn't take advantage of all available CPUs.

On my MacBook Pro (M1 Max, 10 cores), the build can run much faster when build steps are run in parallel.  

On the default GitHub Actions runners (2 core), the build should run a bit faster, and more gains will be seen if/when they provide more cores by default.

Grouping by phase (clean, build, prettier, lint, type check, test, docs) has other benefits.  I changed the `ci-build` script to include a header/separator between each phase, and it makes the logs easier to read.  We can use pnpm's `--aggregate-output` so that the logs within each phase still read sequentially even when the operations are run in parallel.

On my machine, such an approach reduces the time to run the `ci-build` script from 1m45s to 29s.

On GitHub Actions, the `ci-build` script has been taking around 4m40s.  After my changes, it goes down to 2m51s.

**Comment by chrispcampbell** [comment]
To summarize the perf gains:

| machine | before | after |
| -- | --: | --: |
| M1 Max (10 cores) | 1m45s | 29s |
| GitHub Actions (2 cores) | 4m40s | 2m51s |

**Comment by chrispcampbell** [comment]
I'll apply a similar change for the `ci-run-js-int-tests` script.  The improvement is more modest here because there aren't a lot of build/test steps, but may be more useful in the future.

Also, I will change the `ci:int-test` step to use `--aggregate-output` because right now the log messages are interleaved and hard to read in the GitHub Actions logs, especially when there are failures.

| machine | before | after |
| -- | --: | --: |
| M1 Max (10 cores) | 10.8s | 7.7s |
| GitHub Actions (2 cores) | 27s | 22s |

**Comment by travisfranck** [comment]
This is just amazing and cool.  Nice!

**Comment by ToddFincannonEI** [comment]
Very nice! We are making an online build system for the new EPS this fall. I will be taking a look at the SDE build tools with an eye to replacing our old build system, which is much less sophisticated.
