### ISSUE TITLE
could not find commit hash for main

### ISSUE THREAD

**Issue by ulrgol** [climateinteractive/SDEverywhere#388]
Hi, totally new to SDeverywhere and failed during install:
Which template would you like to use? » Default project
✖ Copying project files...
could not find commit hash for main
There was a problem copying the template.
Please file a new issue with the command output here: https://github.com/climateinteractive/sdeverywhere/issues

Urged to open a new issue which I hereby do.
Your help / link to a tutorial / etc. is very much appreciated.
Thanks, Ulrich

**Comment by chrispcampbell** [comment]
Hi @ulrgol, thanks for filing an issue.

This error is most likely to happen if you don't already have Git installed on your machine.  Can you please confirm whether you have Git installed on your machine already (and on your PATH)?  If not, please try installing Git and try the SDEverywhere quick start instructions (the `create` command) again and let me know if you have better luck.

There is some related discussion in this issue for another project that has a similar create script to the one we have in SDEverywhere:
https://github.com/Rich-Harris/degit/issues/37

Some additional context... I forgot that the the [degit](https://github.com/Rich-Harris/degit) library we use for the `@sdeverywhere/create` package assumes that Git is already installed on the machine.  I forgot to note this in the documentation for the `create` package, and we should also mention it in the error message.  I filed a new issue #389 to address those improvements.

**Comment by chrispcampbell** [comment]
As of v0.2.13, the `@sdeverywhere/create` package now works even if Git is not installed locally, so this error should no longer occur.  See #464 for more details.  This should reduce friction for non-technical users who are new to SDEverywhere.  Closing as resolved.
