### ISSUE TITLE
2D array initialization is incorrect when dimensions have matching subscript names

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/SDEverywhere#84]
The C-ROADS model uses a few 2D arrays (constant lists) where the dimensions have matching subscript names, but SDEverywhere does not initialize the array values correctly.  Here is a modification to the existing `arrays_cname` test that demonstrates the issue and causes a test failure:

```
DimC: C1, C2, C3 ~~|
DimC': DimC ~~|

sc[DimC,DimC']=
	11,12,13;
	21,22,23;
	31,32,33;
	~
	~	2D constant array where dimensions have matching subscript names
	|
```

The problem is that in SDE, the code that visits 2D dimensions does lookups based on subscript names, but that breaks down when the "left" and "right" subscripts have the same names.

**Comment by ToddFincannon** [comment]
I tried the subscript alias syntax `DimC' <-> DimC` (see #78) and it had the same problem.
