### ISSUE TITLE
Implement the DELAY FIXED function

### ISSUE THREAD

**Issue by ToddFincannon** [climateinteractive/SDEverywhere#90]
Implement the [DELAY FIXED](https://www.vensim.com/documentation/fn_delay_fixed.html) Vensim function. The delay test model is currently coming up with NaN for many values, so that will need to be fixed first.

**Comment by jrissman** [comment]
It might be worth briefly reviewing duplicate GitHub issue #29 before working on this, in case that thread contains any relevant/helpful info.

**Comment by chrispcampbell** [comment]
@jrissman Good catch, I forgot there was an existing issue for this.  I will close this newer one in favor of #29.  

@ToddFincannon If you can reference #29 in your fix/branch/PR, that would be great.
